#!/bin/bash

if [ $# -ne 1 ]; then
	msg="$0 - Plots a phase space from BIN using delayed coordinates\n
Usage: $0 [BIN]"
	echo -e $msg
	exit 0
fi

if [ ! -e "$1" ]; then
	echo "ERROR: $1 does not exist"
	exit 1
fi

s="set ticslevel 0; set xlabel 'X'; set ylabel 'Y'; set zlabel 'Z'; "
hexdump -e '4/1 "%d " "\n"' "$1" | gnuplot -p -e "$s"'splot "/dev/stdin" u ($3-$4):($2-$3):($1-$2) palette not'
